version: '3'

services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    # declare a database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    entrypoint: ['/bin/sh','-c']
    command:
    - |
       python manage.py migrate
       python manage.py create_cross_timezone_data
    volumes:
      - .:/var/www
    depends_on:
      - db
